services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: mahmoud
      MONGO_INITDB_ROOT_PASSWORD: mahmoud
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mahmoud
      ME_CONFIG_MONGODB_ADMINPASSWORD: mahmoud
      ME_CONFIG_MONGODB_SERVER: mongo
volumes:
  mongo:
